### ISSUE TITLE
Add new GMP limbs functions

### ISSUE THREAD

**Issue by wbhart** [wbhart/mpir#101]
In GMP 6 the following functions occur:

'''
mpz_limbs_read
mpz_limbs_write
mpz_limbs_modify
mpz_limbs_finish
mpz_roinit_n
MPZ_ROINIT_N
'''

We do not have these functions yet. They should be merged from GMP 6.

**Comment by BrianGladman** [comment]
I have done the following in my MPIR repository (master branch):
     1. added the prototypes to gmp_h.in
     2. added the five routines to the mpz directory
     3. added the t-limbs.c test file to the tests/mpz directory
     4. added the necessary build files to Visual Studio 2013, 2015 and 2017
     5. successfully built and run the limb test

The build changes needed to incorporate these changes for *nix/GCC have NOT been done.

**Comment by wbhart** [comment]
I've added this to the *nix build.
