### ISSUE TITLE
mpn_sizeinbase in GMP

### ISSUE THREAD

**Issue by wbhart** [wbhart/mpir#102]
In GMP 6 a new function mpn_sizeinbase has been added. We should merge it from GMP 6.

**Comment by BrianGladman** [comment]
This routine was in our codebase but it was not declared or tested.  I have added a declaration to gmp_h.in and the test from GMP.  I have also added the test to the Visual Studio 2013, 2015 and 2017 builds.

*nix/GCC build integration has NOT been done.

**Comment by wbhart** [comment]
I've now included this in the *nix build.
