### ISSUE TITLE
mpz_get_d() rounds towards zero

### ISSUE THREAD

**Issue by wbhart** [wbhart/mpir#130]
Jeroen Demeyer suggests the following feature:

```
The function mpz_get_d() rounds towards zero. This is incompatible with the usual 
floating-point semantics of rounding to nearest. In C on my machine for example, a 
conversion from unsigned long to double rounds to nearest. Would you agree with 
adding additional functions (or one function with an MPFR-style rounding flag) for 
other rounding modes?
```

We should at least support round down, up and nearest. It could also return a flag to tell you if the value was exact or not.

**Comment by jburse** [comment]
Why closed, what is the solution?

**Comment by wbhart** [comment]
Nobody worked on it in 4 years, so we closed the issue.

You might find it better to make a proposal to the official GMP maintainers and offer some help to implement it for them.
