### ISSUE TITLE
There is no "mpf_log()" "mpf_log2()" or "mpf_log10()" functions.....

### ISSUE THREAD

**Issue by GhostEx** [wbhart/mpir#143]
Thanks for this great project !

There is still no "mpf_log()" "mpf_log2()" or "mpf_log10()" functions so far.

Is it possible to contain these function in the next version ?

Thanks again!

**Comment by wbhart** [comment]
It's unlikely this will be implemented. The mpf module in both GMP and MPIR is basic arithmetic only. It doesn't include implementations of more complicated functions.

Instead you should use the mpfr library (http://mpfr.org/) or implement the functionality you need on top of the primitives provided by GMP/MPIR.
