### ISSUE TITLE
c++11(gcc 4.9) and  mpirxx/mpir.h order of inclusion

### ISSUE THREAD

**Issue by dimpase** [wbhart/mpir#153]
On gcc-4.9.2 the order of inclusion of headers needs to be changed, as suggested [here](https://gcc.gnu.org/gcc-4.9/porting_to.html), as, while compiling C/C++ code including the mpir headers, one otherwise gets 
      
        cstddef:51:11: error: ‘::max_align_t’ has not been declared
             using ::max_align_t;

This was [reported on mpir-devel](https://groups.google.com/d/msg/mpir-devel/78Hb2-sGrjQ/1VohfbjBmgUJ). 

For Sagemath, it is [#18240](http://trac.sagemath.org/18240). Unless there is no MPIR update, with this fixed, this will be patched in Sagemath, cf. [loc.cit.](http://trac.sagemath.org/18240)

**Comment by wbhart** [comment]
Thanks for reporting this. I've applied the patch that Sage developed for this issue.
