### ISSUE TITLE
mpz.fac_ui : ERROR with x64 Release configuration on Visual Studio 2015 

### ISSUE THREAD

**Issue by tomi500** [wbhart/mpir#159]
excerpts from run-tests.py script output:

Testing MPIR Static Library (lib_mpir_k8_k10_k102) in x64\Release Configuration
...
mpz.divis_2exp : success
mpz.export : success
mpz.fac_ui : ERROR ( 3221225477  )
mpz.fdiv : success
...
subc : success
201 tests:
        200 ran correctly
        1 failed
.. completed - press ENTER

(builded with Microsoft Visual C++ 2015 (Enterprise Edition) on Windows 7 - 64 bit)

N.B. with debug configuration all tests are passing

**Comment by wbhart** [comment]
Thanks for reporting this. I've forwarded it to mpir-devel and Brian
Gladman is looking into it.

**Comment by BrianGladman** [comment]
I cannot reproduce this error.   

Testing MPIR Static Library (lib_mpir_k8_k10_k102) in <x64\Release\> Configuration
bswap : success
constants : success
....
rand.rand : success
rand.urbui : success
rand.urmui : success
rand.urndmm : success
subc : success
201 tests:
        201 ran correctly
