### ISSUE TITLE
Compiling error on Windows (file in use)

### ISSUE THREAD

**Issue by thexamx** [wbhart/mpir#160]
![](https://i.gyazo.com/068ace6cf6a17c21e4ebaca7407d7d62.png)

"process can not access the file because it is being used by another process" why?

**Comment by wbhart** [comment]
Probably you need to run with administrator privileges.

**Comment by thexamx** [comment]
Severity	Code	Description	Project	File	Line
Warning		The process cannot access the file 'c:\users\marcin\desktop\mpir-master\build.vc14\x64\release\mpir.pdb' because it is being used by another process.	dll_mpir_core2	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppClean.targets	76

**Comment by BrianGladman** [comment]
This is probably caused by an earlier issue that left the pdb file open.  A Windows restart should fix the issue.
