### ISSUE TITLE
can't support CGAL compilation

### ISSUE THREAD

**Issue by silentmissile** [wbhart/mpir#166]
https://github.com/CGAL/cgal/issues/439
here is the issue reported to CGAL. It was resolved, but we used a mingw compiled gmp instead, so we can't say it's completely resolved.

http://cgal-discuss.949826.n4.nabble.com/compilation-error-in-CGAL-4-7-beta-1-in-VC2015-on-x64-Platform-td4661087.html
some explanation, it seems MPIR is not completely compatible with GMP.

"The problem is that MPIR broke compatibility with GMP (not necessarily for bad reasons), it would work if you were using GMP. (Well, the original problem is that Microsoft chose a weird LLP64 ABI instead of LP64 like everyone else.) We will have to think of a workaround..."

I know it's very hard word, please help us MSVC users

**Comment by wbhart** [comment]
MPIR breaks the API on Windows deliberately. On a 64 bit machine, the _si
and _ui functions should accept 64 bit integers, not 32 bits.

It's unlikely that MPIR is going to change this.

Bill.
