### ISSUE TITLE
yasm binary is installed in MinGW-w64

### ISSUE THREAD

**Issue by wbhart** [wbhart/mpir#167]
Currently make install puts the yasm binary in /usr/bin on MinGW-w64, potentially overwriting a newer Yasm the user has installed. I can't see any reason to do a system install of Yasm.

This was reported by a user called Alexander.

**Comment by sav-ix** [comment]
Just in case, YASM binaries and headers became installed during MPIR build not to 'MinGW-W64/...', but to 'MSYS2/local/...' directory.

**Comment by wbhart** [comment]
See #188

**Comment by sav-ix** [comment]
no bundled YASM => no issue #167

**Comment by masrukajannat466** [comment]
Is it fully resolved ? Why am I still getting this [error](https://trac.macports.org/ticket/57244) on MinGW-w64?

It is still Looking for a system-wide yasm...
