### ISSUE TITLE
Conflict addmul_2/redc_2 with __gmpn_addmul_2

### ISSUE THREAD

**Issue by borneq** [wbhart/mpir#175]
I download fresh version from github. I compile with Visual Studio 2015, Debug, X64.
Project dll_mpir_sandybridge_ivybridge.
in file c:\mpir\build.vc14\dll_mpir_sandybridge_ivybridge\redc_2.obj line 1
Error   LNK2005 __gmpn_addmul_2 already defined in addmul_2.obj

**Comment by BrianGladman** [comment]
This probably means that the sandybridge_ivybridge build files need to be updated.   You can update the files by running mpir_config.py and then selecting the sandybridge_ivybridge option.
