### ISSUE TITLE
ERROR: static library tests need 'mpirxx.lib'

### ISSUE THREAD

**Issue by borneq** [wbhart/mpir#176]
I try compile static mpir with Debug X64
after calling: check_config x64 Debug 14
is error: `static library tests need 'mpirxx.lib'`
Is only mpirxx.h.

**Comment by BrianGladman** [comment]
There are two static libraries for MPIR: mpir.lib for pure C use and mpirxx.lib for those who wish to use C++. The tests are designed to test both of these libraries so you need to build mpirxx.lib as well as mpir'lib in order to build and run the MPIR tests.
