### ISSUE TITLE
Unnecessary WIN64_GCC_PROC in mul_basecase.asm ?

### ISSUE THREAD

**Issue by borneq** [wbhart/mpir#178]
I am testing another GMP + Visual C++ distribution ([ShiftMediaProject/gmp clone](https://github.com/borneq/gmp)) and I use mul_basecase.c instead mpn\x86_64w\sandybridge\mul_basecase.asm because is error in test program.
Error is caused by (for example): 
`int main()
{
    mp_limb_t a[2], b[2], r[4];
    a[0] = 5586368241780752384L;
    a[1] = 1;
    b[0] = 3996824453156700160L;
    b[1] = 12714411616466615L;
    mpn_mul_basecase_asm(r, a, 2, b, 2);
    return 0;
}

`
Probably error in Visual is by WIN64_GCC_PROC, other, correct asm files have FRAME_PROC

**Comment by BrianGladman** [comment]
Can you please supply a simple test program using MPIR alone that demonstrates this issue as I cannot reproduce it.   It appears that you may be trying to use MPIR assembly code with a different GMP distribution. If this is correct, it is not surprising that this doesn't work.
