### ISSUE TITLE
new bugfix release

### ISSUE THREAD

**Issue by xantares** [wbhart/mpir#182]
hello,
I wondered if there would be a new bugfix release in sight,
in particular I'm interested in b84e7e2 which fixes the compatibility with gmp but unfortunately changes the api a bit.
regards,
xan.

**Comment by wbhart** [comment]
We are planning a release at the end of February at this stage.

**Comment by xantares** [comment]
thanks!

**Comment by mpirstate** [comment]
@wbhart Will the bug fix release include a fix for https://github.com/wbhart/mpir/issues/170 ?

I'm basically unable to use MPIR until this is fixed.

**Comment by wbhart** [comment]
I hope so.
