### ISSUE TITLE
Support mpf_t comparison with epsilon

### ISSUE THREAD

**Issue by mpirstate** [wbhart/mpir#183]
It would be really convenient to have `mpf_cmp` versions for epsilon comparison. Maybe both absolute and relative epsilons.

Basically, I want 0.1 + 0.2 to equal 0.3 in my program :) Something better than epsilon available?

**Comment by wbhart** [comment]
No further work on mpf is planned. Please use MPFR [1] if you require
extended functionality.

[1] http://mpfr.org/

**Comment by mpirstate** [comment]
@wbhart What??? I've spend a lot of time integrating MPIR. Are you saying mpf functions are not maintained anymore?

**Comment by mpirstate** [comment]
Damn, this is a bummer. Once #170 got a fix, I was planning to take MPIR live in our system.

**Comment by wbhart** [comment]
The existing mpf functions are maintained. There is no further development
of them beyond what is there now. This is the same situation as exist with
GMP.

Note that MPFR should be faster for many operations than the mpf functions.

We simply don't have the developers to put time into mpf, especially when
all the good floating point implementers are working on MPFR.
