### ISSUE TITLE
Provide cmake support

### ISSUE THREAD

**Issue by sdcb** [wbhart/mpir#186]
With cmake (CMakeLists.txt), we can easily support more than one VS version and UWP builds. Related here: https://github.com/wbhart/mpir/issues/177

**Comment by chfast** [comment]
Has anyone started working on this?

**Comment by wbhart** [comment]
I don't know. You could ask on this ticket
https://github.com/wbhart/mpir/issues/214

**Comment by chfast** [comment]
https://github.com/wbhart/mpir/pull/215

**Comment by wbhart** [comment]
We have decided not to follow through with this.
