### ISSUE TITLE
Support new GMP mpn_divexact_1, mpn_zero_p, and mpn_cnd_swap functions

### ISSUE THREAD

**Issue by wbhart** [wbhart/mpir#191]
GMP 6.1.0 added new functions mpn_divexact_1, mpn_zero_p, and mpn_cnd_swap.

**Comment by Wetitpig** [comment]
But it is not yet supported.

Also, a lot of assembly files have been added for libgmp. It runs much faster now. Can anyone write the Makefile.am again to support this?

Otherwise, can I build the fft/ C files with libgmp? Thanks

**Comment by BrianGladman** [comment]
We don't have cnd_add_n or cnd_sub_n either.  There are also bsqrtinv, bsqrt, brootinv and broot as well. Quite a lot of division code is different but its hard to work out whether we are missing anything here.  A lot of this looks easy to add so I think I can take on the four functions you mention (if not more).

**Comment by BrianGladman** [comment]
The mpn_cnd_* function are those intended for cryptographic operations, which we have agreed not to include in MPIR because libraries such as GMP and MPIR are not suitable for such uses.

**Comment by wbhart** [comment]
Yes, we can exclude those.

**Comment by BrianGladman** [comment]
I compared the file gmp_h.in from GMP and MPIR and found some discrepancies.  These functions are in GMP but not in MPIR:

mpf_cmp_z
mpn_zero_p
mpn_pefect_power_p

Strangely we have these functions in our source code but not in mpir.h (i.e. they are missing in our gmp_h.in): 

mpn_divexact_1
mpn_divrem

So I intend to correct gmp_h.in for the latter two and add the former three.

**Comment by wbhart** [comment]
Fixed in master.
