### ISSUE TITLE
Support Broadwell

### ISSUE THREAD

**Issue by wbhart** [wbhart/mpir#198]
Intel Family 6, Model 61 is known to be Broadwell. cpuid and configure.ac need updating for this arch (the latter specifies the directories, in order, that should be checked for assembly code, e.g. haswell/broadwell. haswell/avx, haswell, etc.), and tuning needs to be done, placing the gmp-mparam.h file in mpn/x86_64/haswell/broadwell.

Also, Broadwell can probably run much of the Skylake assembly, but it isn't known whether that will be slower or faster. The speed program can be used to time the individual assembly files to see which actually benefit the Broadwell arch. Sometimes picking older assembly files can also speed things up too, rather than picking ones that are in the standard directory lineup for broadwell.

Also see #209

**Comment by wbhart** [comment]
I've added rudimentary Broadwell support. It doesn't do anything except use the Haswell assembly. But at least it is there ready for a volunteer to add Broadwell assembly.

@isuruf It would be great if you could test this and send us tuning values for Broadwell (I don't have access to such a machine to test or tune on).

**Comment by isuruf** [comment]
It works and here are the tuning values.
https://gist.github.com/isuruf/2c8d4d6417812865757169e09e48062d

**Comment by isuruf** [comment]
I'll have a look. One thing I can do is to use the adx code from skylake since broadwell supports it too.

**Comment by wbhart** [comment]
Yeah, it may not be faster though. The only way to know is to go through
one file at a time and compare the speeds.

**Comment by wbhart** [comment]
Here are the steps for supporting this architecture

The steps to support this architecture are the follow. Each step gives better support than the previous step:

* Put any new cpuid Family/Models corresponding to broadwell in cpuid.c
* Go through all assembly code in MPIR which runs on broadwell (e.g. from Skylake) and use the speed program to determine which implementations are the fastest for broadwell. If they aren't already in the path, put them in the broadwell directory
* Write new assembly code to support new features of broadwell the number of integer ports, AVX revision, etc. Agner Fog's assembly tables will be useful here.
* Check to see if any of the GMP assembly code is faster and include it.
* Superoptimise the assembly code using the ajs superoptimiser (written for MPIR) https://github.com/akruppa/ajs/
* Tune using tuneup

**Comment by wbhart** [comment]
I believe some limited support has been added. No further changes will be made, most probably.
