### ISSUE TITLE
OS X 10.11 and above not supported

### ISSUE THREAD

**Issue by wbhart** [wbhart/mpir#207]
MPIR fails continuous integration tests on OSX 10.11 and above due to disabling of DYLD_LIBRARY_PATH for security reasons.

A Mac expert will have to sort this out, as we don't have such an expert in the MPIR project at present.

Note that whether or not one gets OSX 10.11 or above on Appveyor seems to be a matter of luck.

**Comment by isuruf** [comment]
You can set which version of OSX to use in travis.yml by setting osx_image. https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version.

I think I saw failures with flint2, but not mpir. Do you have any logs?

**Comment by wbhart** [comment]
Hmm, you might be right. Looking through the history, I only see one
failure due to some bizarre error (presumably unrelated), which seems to
have gone away. Perhaps there's no problem on OSX 10.11 after all.

Anyway, I guess we can set the OSX version for Flint so that it passes.
I'll sort this out some time.

I'll close this issue for now then.
