### ISSUE TITLE
Some Haswells/Broadwells reportedly don't support BMI2

### ISSUE THREAD

**Issue by wbhart** [wbhart/mpir#209]
Some Haswell's reportedly don't support all the Haswell New Instructions. In particular, they don't support BMI2. In cpuid.c we should be checking for bmi2 support.

We currently have haswell and haswell/avx directories, the purpose of which is unclear. I suspect this should be haswell and haswell/bmi2 corresponding to haswell and haswellbmi2 processor names in cpuid.c.

I recall we didn't bother with bmi2 because haswells that don't support it are exceptionally rare. Even Wikipedia says that all Haswells support bmi2. However, if someone using MPIR encounters such a machine, we can add support for it.

**Comment by wbhart** [comment]
It seems like the same distinction might have continued in distinguishing Broadwell H and Broadwell E!!

**Comment by embray** [comment]
Is it possible this could be one of those CPUs?  It is Haswell, but it's getting an Illegal Instruction error when trying to build something against MPIR: https://groups.google.com/d/msg/sage-devel/fNO6bi54gpI/pEwvTV1bDQAJ

**Comment by embray** [comment]
Indeed, the CPU flags don't list bmi1 or bmi2 (whereas on my machine which is an i7 with the Haswell architecture does have bmi1 and bmi2 listed.

**Comment by wbhart** [comment]
Yes, those are not supported. You can try forcing a build for a prior
architecture, as explained for the --build flag in the manual. I guess
sandybridge or ivybridge should work.

**Comment by embray** [comment]
I just suggested `--enable-fat`, but that should work too.

After some grepping around I don't think `haswell/avx` is a misnomer, as the code in there uses many avx(2) instructions; the only BMI2-specific instruction I see is `mulx` (which is also only used under `haswell/avx`) so the assumption seems to be that they go hand-in-hand.  Indeed, Odile's CPU doesn't list any AVX support either. 

But then, why would it be compiling code from under `haswell/avx` in the first place?  Or is that just enabled by default for all Haswell CPUs?

**Comment by wbhart** [comment]
That's why there's a ticket for it.

**Comment by embray** [comment]
Well, I'm going to take a stab at a patch.

**Comment by wbhart** [comment]
Knock yourself out. I think the main MPIR repo is currently mine [1] again,
since the people who were working on a release gave up after failing to
reach an agreement on whether MPIR should build "out-of-the-box" on
Windows. Currently no one is working on MPIR, to my knowledge. However, I
am still able to merge working PR's into my repository.

Brian Gladman would probably also gladly merge patches into his repository.

The website currently still says that MPIR is maintained by me. But this is
only half true. The project is now community maintained. I have simply
agreed to merge patches and reject those that degrade performance, or fix
problems for one arch/platform but break it on others.

If you restrict your patch to the appropriate parts of cpuid.c and
configure.ac, probably this bug can be fixed easily enough without breaking
anything else.

[1] https://github.com/wbhart/mpir

>

**Comment by embray** [comment]
I have no idea how the VC project files are maintained so I won't touch those.  The rest is straightforward

**Comment by wbhart** [comment]
That's fine by me. With the appropriate patches on the *nix side, Brian may
be able to work out a similar patch on the Windows side.... or not.
