### ISSUE TITLE
Fat binary on OSX fails

### ISSUE THREAD

**Issue by isuruf** [wbhart/mpir#212]
```
clang -c -DHAVE_CONFIG_H -D__GMP_WITHIN_GMP -I.. -DOPERATION_fat_entry -mmacosx-version-min=10.9 -m64 -I. -I.. tmp-fat_entry.s -fno-common -DPIC -o .libs/fat_entry.o
clang -cc1as: fatal error: error in backend: unsupported symbol modifier in branch relocation
```

Here's a log https://travis-ci.org/isuruf/mpir-feedstock#L1527

**Comment by wbhart** [comment]
Did it ever work on OSX before? I doubt it has ever been supported. Either way, an OSX person will have to take a look at this, because I don't have an OSX machine and have zero knowledge about them.

**Comment by isuruf** [comment]
I dug up an old build log and it had also failed with the same error.

**Comment by wbhart** [comment]
In case someone does try to fix this, it is probably quite a bit of work to support building fat binaries on OSX, if it is even possible.

**Comment by wbhart** [comment]
We don't intend to support fat builds on OSX.
