### ISSUE TITLE
Hunter package and CMake

### ISSUE THREAD

**Issue by chfast** [wbhart/mpir#214]
Hello there,

I plan to package the MPIR for hunter C++ package manager. [Hunter](hunter.sh) is a package manager for C++ projects based on CMake.

I wander if you are interested in having any CMake support here upstream. I assume the build system for MPIR is quite complex, but I can start with something small.

I read the docs about packaging MPIR. Is it good idea to start with a configuration for C implementation only (CPU none)?

**Comment by wbhart** [comment]
As you probably guessed, the MPIR build system is extremely complex since
it has to support arch specific assembly language.

I don't know if our users want CMake support or not. You could ask on the
list to find out.

A C only build should be easier for you to start with.

**Comment by isuruf** [comment]
There was interest here, https://github.com/wbhart/mpir/issues/177

**Comment by chfast** [comment]
https://github.com/wbhart/mpir/pull/215

**Comment by wbhart** [comment]
We don't plan to follow through with this.
