### ISSUE TITLE
Problems building MPIR-3.0.0 on OSX

### ISSUE THREAD

**Issue by lbenet** [wbhart/mpir#217]
Trying to install current Nemo in my Mac, I run into an issue related to building MPIR-3.0.0; see https://github.com/Nemocas/Nemo.jl/issues/183.

Some data about my machine:
- Mac OSX 10.9.5, Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
- Xcode: Version 6.2 (6C131e)
- `gcc --version`: gcc (Homebrew GCC 7.1.0) 7.1.0
- `m4 --version`: GNU M4 1.4.6
- `yasm --version`: yasm 1.3.0

Following the Nemo `deps/build.jl` file I run:
```
$ ./configure --with-yasm=/usr/local/bin/yasm --prefix=/Users/benet/dev/Nemo.jl/local/ --enable-gmpcompat --disable-static --enable-shared
...

$ make -j4
...
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -D__GMP_WITHIN_GMP -I.. -DOPERATION_subadd_n -m64 -O2 -march=corei7 -mtune=corei7-avx -c subadd_n.c  -fno-common -DPIC -o .libs/subadd_n.o
make[2]: *** [mul_1.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

```

@wbhart suggested [in this comment](https://github.com/Nemocas/Nemo.jl/issues/183#issuecomment-305483572) that the problem may be related with the assembler of my machine.

Any suggestions how to get around this?

**Comment by wbhart** [comment]
Thanks for the report. I think you will have to do make, rather than make -j4 so that the cause of the error can be seen. If you can add that information, I'll post on the list about this and see if anyone knows what the problem is or how to solve it.

**Comment by lbenet** [comment]
Sure! This is what I get (I omit details which seem to went through)
```
$ make
...
 gcc -c -DHAVE_CONFIG_H -D__GMP_WITHIN_GMP -I.. -DOPERATION_mul_1 -m64 -O2 -march=corei7 -mtune=corei7-avx -I. -I.. tmp-mul_1.s -fno-common -DPIC -o .libs/mul_1.o
tmp-mul_1.s:95:no such instruction: `mulx (%rsi), %r9,%r8'
tmp-mul_1.s:96:no such instruction: `mulx 8(%rsi), %r11,%r10'
tmp-mul_1.s:97:no such instruction: `mulx 16(%rsi), %rcx,%r12'
tmp-mul_1.s:101:no such instruction: `mulx (%rsi), %rcx,%r12'
tmp-mul_1.s:102:no such instruction: `mulx 8(%rsi), %rbx,%rax'
tmp-mul_1.s:106:no such instruction: `mulx 16(%rsi), %r9,%r8'
tmp-mul_1.s:114:no such instruction: `mulx (%rsi), %rbx,%rax'
tmp-mul_1.s:118:no such instruction: `mulx 8(%rsi), %r9,%r8'
tmp-mul_1.s:122:no such instruction: `mulx (%rsi), %r11,%r10'
tmp-mul_1.s:123:no such instruction: `mulx 8(%rsi), %rcx,%r12'
tmp-mul_1.s:124:no such instruction: `mulx 16(%rsi), %rbx,%rax'
tmp-mul_1.s:135:no such instruction: `mulx (%rsi), %r9,%r8'
tmp-mul_1.s:140:no such instruction: `mulx 8(%rsi), %r11,%r10'
tmp-mul_1.s:142:no such instruction: `mulx 16(%rsi), %rcx,%r12'
tmp-mul_1.s:144:no such instruction: `mulx 24(%rsi), %rbx,%rax'
make[2]: *** [mul_1.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by isuruf** [comment]
Can you try doing `export CFLAGS="-Wa,-q $CFLAGS` and run configure and make?

**Comment by lbenet** [comment]
Thanks for the suggestion! It seems that it has solved the problem.

**Comment by isuruf** [comment]
The problem is that even though your `gcc` is very recent, it was configured with `gas` that comes with OSX which is ancient and does not support the instructions that mpir has detected in your hardware. Basically your software is older than the hardware.

Adding that flag instructs `gcc` to use the assembler that comes with `clang` which is newer and supports the instructions like `mulx`.

You can also use `clang` compiler which has a more up-to-date assembler.

**Comment by lbenet** [comment]
Thanks a lot for the explanation! Indeed, I use the gcc version provided by homebrew, instead of the one provided from apple. I also guess that it is the bottle version.

**Comment by isuruf** [comment]
`gcc` provided by apple uses the same assembler, so that will not work. I think `mpir` should prefer `clang` over `gcc` on OSX if `$CC` is not set.

**Comment by dimpase** [comment]
No, this seems to be an outdated belief. Nowadays gcc provided by Apple is not gcc (it has been for quite a while), it's clang, and it does use a recent clang's assembler, at least with Xcode 9.
E.g. assuming yasm in the path and Xcode command line tools installed, one can simply do
```
./configure CC=cc && make -j6
```
for a successful build.

**Comment by isuruf** [comment]
Ah, so only homebrew's gcc is affected? What about sage's gcc?

**Comment by dimpase** [comment]
As far as I can see, there is no `gas` in Xcode 9 (perhaps hidden somewhere ?). There is `as`, which is the llvm assembler; probably also used by Sage's gcc.

**Comment by cnasikas** [comment]
Hi,

I have the same problem. I tried all suggestion above but I couldn't make it work.

 MacOS: Mojave 10.14.4
 Model Name:	MacBook Pro
 Model Identifier:	MacBookPro13,1
 Processor Name:	Intel Core i5
 Processor Speed:	2 GHz

Xcode: 10.2 Build version 10E125

`gcc --version`

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
`m4 --version`: GNU M4 1.4.6

I run

```
./configure --enable-cxx --prefix="~/local/mpir"`

....

make

....

ld: in section __DATA,__const reloc 0: X86_64_RELOC_SUBTRACTOR must have r_extern=1 file 'mpn/.libs/addmul_1.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libmpir.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

```

When I set `export CFLAGS="-Wa,-q $CFLAGS"` I get 

```
checking build system type... skylakeavx-apple-darwin18.5.0
checking host system type... skylakeavx-apple-darwin18.5.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=64
checking compiler gcc -Wa,-q  ... no
checking whether cc is gcc... yes
checking compiler cc -Wa,-q  ... no
checking ABI=32
checking compiler gcc -Wa,-q  ... no
checking compiler icc -Wa,-q  ... no
checking whether cc is gcc... yes
checking compiler cc -Wa,-q  ... no
configure: error: could not find a working compiler, see config.log for details
```

Setting only `-Wa` works. The problem is with `-q` argument. I tried also setting `CC=cc`, `make -j4` without luck.

Any suggestions ?

Thanks in advanced

**Comment by dimpase** [comment]
this is a different problem, related to linking, rather than outdated assembler.
