### ISSUE TITLE
mpz_perfect_power_p returning more than yes/no?

### ISSUE THREAD

**Issue by rwst** [wbhart/mpir#218]
Is it possible to return the root and/or the exponent when `mpz_perfect_power_p` found a power? It seems a waste to use this function and write code that finds the root afterwards.

**Comment by wbhart** [comment]
It would be good to have this. However, it would have to be a different
function, since it is less efficient to return the power that to tell if it
is a perfect power, simply because returning the power would have to have
some kind of consistent semantics, such as returning the largest power.

**Comment by wbhart** [comment]
We are closing some MPIR feature request issue. Please see forthcoming announcement on the mpir-devel list in the next few days.
