### ISSUE TITLE
Configuring from command line on windows

### ISSUE THREAD

**Issue by smtrat** [wbhart/mpir#219]
In older versions, a `configure.bat` existed to set parameters from the command line. As of the current release (3.0.0), it is no longer there. If I were to build this library from the command line (for example in appveyor), how would I set `--enable-gmpcompat` or `--enable-shared`? (I don't want a cygwin or MinGW build, but e.g. `build.vc15`)

**Comment by wbhart** [comment]
To my recollection, configure.bat was unmaintained, and eventually broke.
But we use appveyor, so you can check in the relevant files to see how we
do that.

--enable-gmpcompat and --enable-shared are Linux specific.

**Comment by smtrat** [comment]
I did look into your appveyor.xml and you don't use these parameters. That's why I asked.
Given that your quote states that these are linux specific, I assume that I have to rename the library files manually from mpir to gmp. This is not a big problem.

The actual (more important) problem for me is, whether there is a way to get a `mpirxx.dll`.

**Comment by wbhart** [comment]
The details at the top of build.vc14/msbuild.bat show what's available. You can build a dll, but I don't see an option there for building an mpirxx.dll. I'm not sure if the C++ library is built by default or not. Perhaps @BrianGladman knows?

**Comment by BrianGladman** [comment]
mpir.dll combines both the c and c++ functionality.
