### ISSUE TITLE
MD vs MT

### ISSUE THREAD

**Issue by isuruf** [wbhart/mpir#220]
I'm trying to use MPIR (compiled with `/MT`) and another library compiled with `/MD`. This leads to link errors if I try to compile statically. When compiling a DLL with /MD it goes fine, but there might be issues as in, https://msdn.microsoft.com/en-us/library/ms235460.aspx

Is there a way to switch to `MultiThreadedDLL` for the dll build?

Also, what was the reason to switch from `MultiThreadedDLL` to `MultiThreaded` CRT for dlls in https://github.com/wbhart/mpir/commit/7217b15eea5337963c147bf1adf89a4206eeaf41 ?

**Comment by isuruf** [comment]
> Is there a way to switch to MultiThreadedDLL for the dll build?

cc @BrianGladman

**Comment by BrianGladman** [comment]
Static and dynamic MPIR libraries are built with the run-time library of the same type.  So, for example, mpir.lib uses the MultiThreaded run-time libraries, while mpir.dll uses the MultiThreadedDLL run-time libraries.

So MPIR dynamic link libraries are ***already*** built using the MultiThreadedDLL run-time libraries.

It hence seems that you may be trying to use MPIR ***static*** libraries linked to other libraries or applications that themselves use the DLL run-time libraries.   If this is correct, you can switch these static libraries to use the DLL run-time libraries by editing the appropriate line in the files:

    mpir_release_lib.props
    mpir_debug_lib.props

now:
```
        <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
        <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>

```
to:
```
        <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
        <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>

```
The  commit 7217b15 did not change the run-time libraries used in building MPIR versions.  Historically Microsoft MSVC linked static and dynamic library builds to run-time libraries of the same type. But around the time of this commit they changed this policy and linked both types of library to the DLL run-time libraries.  

The aim of this commit was to negate this MSVC change and continue with the MPIR policy of linking MPIR builds to run-time libraries of the same type. This was done to avoid the many problems that users have with DLL run-time library installation when using MPIR static libraries. 

I have proposed that we change to the use of the DLL run-time libraries even when building the MPIR static libraries but this has not been a suggestion that MPIR users have universally welcomed.

**Comment by wbhart** [comment]
I assume this was resolved. Feel free to discuss with BG if not.
