### ISSUE TITLE
mpir build on Windows Win32

### ISSUE THREAD

**Issue by qufish** [wbhart/mpir#228]
When I alter the build.vc15\lib_mpir_core2.vcxproj project to create Win32 libraries the environment command to yasm is '-f Win32' which is being rejected, apparently it must be '-f win32' lowercase which works manually.  This project normally outputs x64 lib code.  Latest yasm download.

**Comment by ChillMagic** [comment]
There is a bug in 'yasm':
https://tortall.lighthouseapp.com/projects/78676/tickets/276-format-win32-fails-default-platform-name-in-vs

This bug is fixed in 2014.10, but it is not build to release. (The newest release is in 2014.8).

You can rebuild vsyasm to fix this bug.

**Comment by wbhart** [comment]
I assume this support request was closed.
