### ISSUE TITLE
Label macros missing

### ISSUE THREAD

**Issue by wbhart** [wbhart/mpir#233]
The labels and jumps to labels in [1] and [2] require L() to be wrapped around them (and decimal points omitted). This is required for JMPENT to work on OSX.

[1] https://github.com/wbhart/mpir/blob/master/mpn/x86_64/mullow_n_basecase.asm
[2] https://github.com/wbhart/mpir/blob/master/mpn/x86_64/sqr_basecase.asm

**Comment by dimpase** [comment]
It seems that all what matters is decimal points, which might tell the OSX linker to make them symbols. On OSX the `L()` wrapper merely prepends `L`, as far as I can tell.

**Comment by wbhart** [comment]
I believe this is fixed in master.
