### ISSUE TITLE
Release tags on git seems to be lagging compare to the official website

### ISSUE THREAD

**Issue by jasjuang** [wbhart/mpir#240]
In http://mpir.org/downloads.html mpir is already till version 3.0.0 but in https://github.com/wbhart/mpir/releases mpir is only released till 2.7.0. I am trying to setup an automated CI workflow that pulls from git and read the latest tags. Can we update the tags on git?

**Comment by wbhart** [comment]
I tried to tag the mpir-3.0.0 branch as a release on GitHub. I don't know
if that is what you are after.

**Comment by jasjuang** [comment]
Yes that's exactly right, thanks!
