### ISSUE TITLE
mpf_class and mpz_class ostream& operator<< fails: LNK2019

### ISSUE THREAD

**Issue by SASUPERNOVA** [wbhart/mpir#241]
I tried using std::cout to print the mpf_class and got the following error:

`main.obj:-1: error: LNK2019: unresolved external symbol "__declspec(dllimport) class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,struct __mpz_struct const *)" (__imp_??6@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV01@PEBU__mpz_struct@@@Z) referenced in function main`

The same issue also occured when I tried using the mpz_class. 

The commands I used to compile the libraries were the following:

```
./configure --disable-static --enable-shared --enable-cxx
make -lmpirxx -lmpir
```

Additionaly, I used the following commands in "_Developer Command Prompt for VS2015_" to generate the required .dll.lib files (Qt Creator 4.4.1 was giving me errors during their absense):

```
lib /def:libmpir-3.def /out:libmpir.dll.lib /MACHINE:"X64"
lib /def:libmpirxx-3.dll.def /out:libmpirxx.dll.lib /MACHINE:"X64"
```
I took the above .def files from the .lib folder generated after executing make.

Some additional details that might be helpful:

- OS: Windows 7 Ultimate
- Tool used for MPIR compilation: [MSYS2](http://www.msys2.org/)
- gcc & g++ version of MSYS2: 7.2.0
- yasm version: 1.3.0
- Compiler used for Qt project: qmake

**Comment by isuruf** [comment]
You can't mix msys2 libraries and msvc libraries. Either compile MPIR using the visual studio solution files given  so that both projects use MSVC or compile your project using MSYS2 so that both projects use MSYS2
