### ISSUE TITLE
Travis CI OSX gcc build is broken

### ISSUE THREAD

**Issue by dimpase** [wbhart/mpir#246]
See e.g. https://travis-ci.org/wbhart/mpir/jobs/338737718 - this is probably due to Homebrew updating gcc..

**Comment by wbhart** [comment]
It's not the only problem. The CPU is also too new to be detected.

**Comment by dimpase** [comment]
I have the travis OSX gcc build passing with the default Homebrew gcc,
version 7.3.

I don't know why your travis tests insists on gcc 4.8.

**Comment by dimpase** [comment]
@isuruf - you seem to have been setting gcc to 4.8 on OSX for Travis CI - was that for a reason? It's not working any more. Using the default Homebrew gcc (7.3) works.

**Comment by wbhart** [comment]
I think that was done back in 2016.

**Comment by isuruf** [comment]
> you seem to have been setting gcc to 4.8 on OSX for Travis CI - was that for a reason?

4.8 was just a arbitrary choice. I wanted to add a versioned gcc because having a fixed version makes it one less thing to debug when something goes wrong.

**Comment by dimpase** [comment]
fixed by #245
