### ISSUE TITLE
[Enhancement] Allow tuneup to automatically update gmp-mparam.h

### ISSUE THREAD

**Issue by BrainStone** [wbhart/mpir#253]
Hi, it would be really cool if the `tuneup` would get a small improvement:

A flag that switches the behavior so that instead of outputting the new parameters for `gmp-mparam.h` it directly writes them.

Another useful flag would be the `-h` flag that prints the usage message that's currently hidden in the source code.

**Comment by BrainStone** [comment]
For the people that would need a solution now or in case this doesn't get added, here is a little script that does it:

```
./tuneup > gmp-mparam.h 2> tuneup.log
mv -f gmp-mparam.h "$(head -n1 tuneup.log | sed 's/^.*\.\//..\//')"
rm tuneup.log
```

Here is what the sed command does in case some is confused: https://regex101.com/r/9s2vTa/1  
The text in the "TEST STRING" text box is the first line of `tuneup.log`.  
The whole thing could maybe be made a little more robust, that should do the trick for as long as the first lines ends in a path that starts with `./` (indicating a relative path)

**Comment by wbhart** [comment]
We are closing many MPIR issues. Please see forthcoming announcement on the mpir-devel list in the next few days.
