### ISSUE TITLE
test failure on beaglebone black

### ISSUE THREAD

**Issue by jessup** [wbhart/mpir#269]
t-mul_fft_main runs out of memeory when run on a beaglebone black. Reducing the maximum depth in the main loop of t-mul_fft_main.c fixes this. Seems like the test was just beyond the capacity of the system, and everything is probably fine; are there other diagnostics I could try in order to make sure the compiled code is working as expected?

**Comment by wbhart** [comment]
There's no other tests that you can run. If you are sure it is using all the memory on the machine, that's very likely the problem. The FFT is pretty memory hungry.
