### ISSUE TITLE
The build system is broken.

### ISSUE THREAD

**Issue by slavaim** [wbhart/mpir#284]
It would be nice if you keep installation instructions in sync with the project. There is no ./configure file in the current main branch.

**Comment by DenVG** [comment]
How it was resoveld? Or where to get releavnt build insructions?

**Comment by musicinmybrain** [comment]
Usually people don’t track the generated `configure` script in git. A properly generated release tarball does have it; the ones here don’t, so use the ones from http://mpir.org/downloads.html and you’re all set. Or, run the included `autogen.sh` script to create the `configure` script; you’ll need autoconf/automake/libtool installed locally in this case.
