### ISSUE TITLE
Merge GMP's mpz_powm and mpz_powm_ui

### ISSUE THREAD

**Issue by wbhart** [wbhart/mpir#83]
Merge GMP's mpz_powm and mpz_powm_ui.

This requires the following functions from GMP:

mpz/powm.c
mpz/powm_ui.c
mpn/binvert.c
mpn/powlo.c
mpn/powm.c

(Also check for assembly versions.)

All of these use GMP's mpn_mullo_n which writes only n limbs, not 2n as our mpn_mullow_n does. A lot of careful work is required to sort this out.

Furthermore, the _ui function needs to take an mpir_ui. It fakes up an mpz from this, so some code needs to be modified to handle it correctly.

**Comment by jpflori** [comment]
Pull request at https://github.com/wbhart/mpir/pull/193
